### ISSUE TITLE
toData有默认数据要怎么做？fromData的数据内还是有与toData重复的数据

### ISSUE THREAD

**Issue by Gmle7** [hql7/tree-transfer#10]
我需要给toData框放一些默认值，但是放进去之后，fromData里重复的数据并没有消失，我应该怎么做才可以给toData赋默认值，是否只能点击往右的按钮传过去？

**Comment by Gmle7** [comment]
能不能我给出fromData的一部分id，toData就能展示这些id的相关数据

**Comment by Gmle7** [comment]
大概就是，我给出一些id值，formData就选中相关的数据，然后执行add穿梭，toData得到数据。这一步用户不感知，就相当于给toData赋了默认值了。

**Comment by cseve123** [comment]
相当于是根据id重formData中反显toData，看组件中有对树的遍历，这个id反查好做么
