### ISSUE TITLE
开启懒加载,右侧数据向左侧移动时数据未成功渲染上去

### ISSUE THREAD

**Issue by 516708843** [hql7/tree-transfer#102]
版本：2.2.9
遇到问题：当我将一个包含子节点的非一级节点移动到右侧后，左侧节点隐藏/消失。此时将这些节点左移不会渲染到页面上。
而当左侧父节点存在时能正常渲染。
想法：是不是需要调用隐藏展示之类的方法将左侧节点显示出来啊。非专业前端，如果问题太基础不要见怪。

**Comment by hql7** [comment]
懒加载有问题，不建议使用
