### ISSUE TITLE
请问如果不用npm，直接cdn 方式怎么使用

### ISSUE THREAD

**Issue by nobt** [hql7/tree-transfer#103]
类似这样该怎么写呢
![QQ图片20200708201354](https://user-images.githubusercontent.com/9441813/86917374-94252800-c157-11ea-9574-29c039bd7477.png)

**Comment by hql7** [comment]
script引入 https://unpkg.com/browse/el-tree-transfer@2.3.0/dist/treeTransfer.min.js
