### ISSUE TITLE
弹出穿梭框后导致原页面的body的css改变了，需要重新刷新页面才正常

### ISSUE THREAD

**Issue by lidongyue-Frank** [hql7/tree-transfer#111]
弹出穿梭框后
![image](https://user-images.githubusercontent.com/40556686/93325122-63452b80-f849-11ea-8a7a-a5a770193659.png)

弹出穿梭框前
![image](https://user-images.githubusercontent.com/40556686/93325084-558fa600-f849-11ea-8721-f6f89fa61b92.png)

**Comment by hql7** [comment]
#121
