### ISSUE TITLE
回显后,左侧数据栏没有去重

### ISSUE THREAD

**Issue by St-coder** [hql7/tree-transfer#112]
若手动去重,花费的时间太长了,不具有经济性.

建议下一个版本,出一个**能支持  左侧树形结构,右侧通讯录结构的穿梭框,这样编辑的时候能更好的回显**.就不用将选中的树形结构传给后台,

**Comment by namecho** [comment]
我也遇到回显没有去重的问题，修改回显，后台返回右侧树结构，左侧也有相同的树结构

**Comment by EdisonYoung23** [comment]
同求

**Comment by hql7** [comment]
很奇怪的要求，左侧树右侧列表，右侧不就没有结构性了吗，加入每个父节点下都有一个同样名字的子节点，右侧列表形式如何区分；回显时看说明：左侧和右侧加载一起是一个完整的树，如果左侧不应该是全部，而应该是未授权，右侧应该是已授权。如果非要左侧全部，可以根据返回的已授权keys使用defaultTransfer默认穿梭一次，右侧不需要赋初始值。 @St-coder @EdisonYoung23 @namecho
