### ISSUE TITLE
点击向右穿梭，子级不见了，也不会报错

### ISSUE THREAD

**Issue by newsun007** [hql7/tree-transfer#117]
你好，我这边点击向右穿梭，子级不见了，也不会报错。左右穿梭都可以，但是子级一穿梭就不见不显示了，请问是什么问题？

**Comment by bydzjmx** [comment]
> 你好，我这边点击向右穿梭，子级不见了，也不会报错。左右穿梭都可以，但是子级一穿梭就不见不显示了，请问是什么问题？

请问解决了吗，我这边也遇到了这个问题

**Comment by hql7** [comment]
子级pid要对应父级id，id不可重复
