### ISSUE TITLE
按钮回调事件和vue冲突

### ISSUE THREAD

**Issue by EdisonYoung23** [hql7/tree-transfer#119]
Event "addbtn" is emitted in component <TreeTransfer> at lib/transfer-extend.vue but the handler is registered for "addBtn". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "add-btn" instead of "addBtn".

**Comment by hql7** [comment]
@EdisonYoung23 v2.4.1以上已改为 @add-btn
