### ISSUE TITLE
组件自带的clear.css 会作用全局，和项目中的样式冲突

### ISSUE THREAD

**Issue by unpanda7** [hql7/tree-transfer#121]

**Comment by zoukangdlut** [comment]
@hql7 你好，我也遇到了这种情况，如果不刷新页面如何避免这种情况呢？

**Comment by hql7** [comment]
@zoukangdlut @unpanda7 这可咋整哦，加scoped会影响之前的用户，不加会污染全局样式，有啥建议

**Comment by unpanda7** [comment]
你组件包个 class，需要reset的css 在 class 范围应该可以， 没必 reset 默认css

**Comment by xiexiangbo** [comment]
@hql7 兄弟 要是加scoped应该在哪里加呢 在sourceContent那里加吗

**Comment by zoukangdlut** [comment]
@hql7 我现在想单独引用你src里面的文件尝试一下能否解决这个css污染问题，但是发现vue中import { arrayToTree } from "./array.js";  这个js文件在哪？

**Comment by Johnnyyuu** [comment]
Met the same PROBLEMS, couldn't find "./array.js"! :(

**Comment by zoukangdlut** [comment]
@unpanda7 @hql7 @Johnnyyuu @xiexiangbo 我找到了这个函数，通过源码方式引的时候就不会出现css样式污染了

arrayToTree(arr, nodeKey, parentKey) {
      if (!Array.isArray(arr) || !arr.length) {
        return []
      }
      let map = {}
      arr.forEach((item) => {
        const key = item[nodeKey]
        map[key] = item
      })
      let tree = []
      arr.forEach((item) => {
        const parentId = item[parentKey]
        const parent = map[parentId]
        if (parent) {
          if (!parent.children) {
            // this.$set(parent, 'children', [])
            parent.children = []
          }
          parent.children.push(item)
        } else {
          tree.push(item)
        }
      })
      return tree
    }

**Comment by hql7** [comment]
@zoukangdlut @Johnnyyuu src里的源码不是最新的，lib下的是，arrayToTree 目前使用wl-core里的，
yarn add wl-core;  import { arrayToTree, valInDeep } from "wl-core";

**Comment by zoukangdlut** [comment]
@hql7     tree-transfer/src/components/transfer-extend.vue 我是通过源码引的，我发的这个文件里引入了一个clear.css ，把这个引掉后就没出现过css污染问题

**Comment by zoukangdlut** [comment]
@hql7 多谢兄弟

**Comment by hql7** [comment]
@zoukangdlut @unpanda7 @Johnnyyuu @xiexiangbo v2.4.3将clear.css移除
