### ISSUE TITLE
更新2.4.1 后左侧节点无法渲染，右侧节点正常

### ISSUE THREAD

**Issue by jovian007** [hql7/tree-transfer#127]
更新2.4.1 后左侧节点无法渲染，右侧节点正常

**Comment by hql7** [comment]
@jovian007 能否提供demo？此项目运行的2.4.1版本未发现有节点无法渲染的情况

**Comment by jovian007** [comment]
更新后有点变化，是我这里的问题，已经可以渲染了，谢谢哈
