### ISSUE TITLE
2.4.2版本 更新后，左侧数据穿梭到右面正常，穿回来会产生两个一样的父节点

### ISSUE THREAD

**Issue by jovian007** [hql7/tree-transfer#129]
2.4.2版本 更新后，左侧数据穿梭到右面正常，穿回来会产生两个一样的父节点。
同时报错
`vue.runtime.esm.js:619 [Vue warn]: Duplicate keys detected: '280'. This may cause an update error.`
![image](https://user-images.githubusercontent.com/32379562/102446033-d6885480-4067-11eb-9c45-bf3931793ca4.png)

**Comment by jovian007** [comment]
重复的节点的父节点pid=0,id=280, 按理穿梭回左侧的节点应该与原节点是同一个节点，可是产生了两个一模一样的节点

**Comment by hql7** [comment]
@jovian007 demo中操作了几次无法重现，正好2.4.3重构了穿梭逻辑，可以尝尝鲜

**Comment by jovian007** [comment]
> @jovian007 demo中操作了几次无法重现，正好2.4.3重构了穿梭逻辑，可以尝尝鲜

好的，我升级试试，谢谢哈
