### ISSUE TITLE
从详情到编辑的反显

### ISSUE THREAD

**Issue by cseve123** [hql7/tree-transfer#16]
场景：当新建内容后，回来编辑一般接口只会告诉我选的id，意味着我要把原来的树做拆分成form_data和to_data，才能达到我之前选中的情况，那这样对于原树的构建和层级很深情况下，工作量是不是会很大了,虽然通过defaultCheckedKeys可以让左侧勾选，但业务场景应该这些执行一次addToAims

**Comment by hql7** [comment]
1.9.7版本增加此功能

**Comment by fadeds** [comment]
设置了deraultcheckkeys为[1,2] 在设置defaultTransfer 为true，造成死循环
