### ISSUE TITLE
左边的tree点击右边不会添加

### ISSUE THREAD

**Issue by SummerMJ** [hql7/tree-transfer#2]
右边的toData一定要有初始数据吗？是个空数组行不行

**Comment by SummerMJ** [comment]
pid和id需要什么规律吗?我用的demo的格式ok,我自己的格式加上pid和id又不行了

**Comment by SummerMJ** [comment]
我用你的demo的初始数据ok的,我自己的数据加上pid和id就不行了

**Comment by hql7** [comment]
第一层数据的pid应定义为0
id应为字符型，最新版本支持id为数值型

在 2018-07-26 11:30:17，"Summer" <notifications@github.com> 写道：


pid和id需要什么规律吗?我用的demo的格式ok,我自己的格式加上pid和id又不行了

**Comment by zhangwei900808** [comment]
我也遇到相同问题
