### ISSUE TITLE
采用defaultCheckedKeys和 defaultTransfer参数，左边表格样式问题

### ISSUE THREAD

**Issue by Summer-Lin** [hql7/tree-transfer#20]
默认数据赋值给defaultCheckedKeys，然后让defaultTransfer自动穿梭到右边
但左边不应该显示蓝色样式吧？
![image](https://user-images.githubusercontent.com/26006995/50804419-ccf8fc80-1328-11e9-8ddf-693d50aa64fb.png)

**Comment by hql7** [comment]
@Summer-Lin 是个瑕疵，列入规划
