### ISSUE TITLE
有没有办法默认不可选

### ISSUE THREAD

**Issue by atheist1** [hql7/tree-transfer#26]
有没有办法默认不可选

**Comment by hql7** [comment]
@atheist1 

> {
>      id: 5,
>     label: '三级 3-1-2',
>     disabled: true
> }
数据里加disabled字段即可，

disabled | 指定节点选择框是否禁用为节点对象的某个属性值 | boolean, function(data, node)

**Comment by sshien** [comment]
default-expanded-keys 为何不把el-tree 这个属性加上呢
