### ISSUE TITLE
使用自定义字段穿梭后，右边的没有成为树状结构，直接列表了

### ISSUE THREAD

**Issue by Nicolas-shanpao** [hql7/tree-transfer#28]
![image](https://user-images.githubusercontent.com/28480091/51590195-18fc9180-1f24-11e9-897c-8b95b33b3a13.png)
如图，层级有点多，不知道是怎么回事

**Comment by hql7** [comment]
@Nicolas-shanpao 检查自定义字段用法是否有误，如有问题请提供最小可重现demo
