### ISSUE TITLE
筛选后选择父节点，未显示的子节点也会被选中？

### ISSUE THREAD

**Issue by ziyiorziyi** [hql7/tree-transfer#32]
例如demo中的数据，搜索框输入数字5，选择11-4，11-4下面左右子节点全部被移到右侧？如果只想转移显示的（筛选）数据，如何操作？谢谢

**Comment by hql7** [comment]
筛选不会改变原数据，因此穿梭后的还是带着子节点的，可以fork一份源码自行修改一下
