### ISSUE TITLE
如何动态添加子节点数据

### ISSUE THREAD

**Issue by BackTooHard** [hql7/tree-transfer#34]
异步请求的数据动态加到父节点children没有更新视图。

**Comment by hql7** [comment]
暂时没有将load lazy引入，待开发

**Comment by BackTooHard** [comment]
恩恩 好的

**Comment by hql7** [comment]
@BackTooHard 2.2.0已添加lazy功能，但是左右两侧都开放了懒加载，具体影响可能会有控制外的问题。因此在懒加载回调函数中增加用于判断来自左侧还是右侧回调的返回值
