### ISSUE TITLE
您好！就是穿梭框的兄弟树形表格 有点问题想问下作者是你吗？

### ISSUE THREAD

**Issue by liwenbin1988** [hql7/tree-transfer#35]

**Comment by liwenbin1988** [comment]
除了treeTableSelect 这个事件，treeTableClick 和openChildren这两个事件都不能用function(row){console.log(row)}打印里面的row是undefined

**Comment by hql7** [comment]
@liwenbin1988 已修复

**Comment by liwenbin1988** [comment]
@hql7 还是不行！
<treeTable :data="tree_table" :columns="columns" checkBox expandAll parentChild border :options="{key:'id', children:'Children'}" @treeTableSelect="getTreeTableSelect" @openChildren='openChildren' @treeTableClick='treeTableClick'/>
getTreeTableSelect(val){
      console.log(val);
    },
    openChildren(val){
      console.log(val);
    },
    treeTableClick(val){
      console.log(val);
    },
打印出来还是 undefined

**Comment by hql7** [comment]
@liwenbin1988 见右侧源码
