### ISSUE TITLE
为什么左边是树形右边就变成了列表

### ISSUE THREAD

**Issue by loveameko** [hql7/tree-transfer#36]
为什么左边是树形右边就变成了列表
![image](https://user-images.githubusercontent.com/50290546/57191898-35658c80-6f5d-11e9-8363-534ca8bd9648.png)
代码如下：
<tree-transfer :from_data="workType" :to_data="dest" :default-props="{ children: 'children',label:'typeName' }" :mode="mode" @addBtn="add" @removeBtn="remove"></tree-transfer>

**Comment by hql7** [comment]
@loveameko id如pid没有指定的话请确认数据字段是否为id和pid，使用前请参照文档或clone运行示例。如问题仍未解决请提供最小可复现例子

**Comment by fadeds** [comment]
那是你的pid没有设置，除了第一层级是0，子节点都是父级id，就不会出现了

**Comment by jwencode** [comment]
根据官方案例修改

将formData id改为code,pid改为parentId,通过设置defaultProps属性做参照，同样右侧不显示树结果

![image](https://user-images.githubusercontent.com/30517801/64922571-36f46a80-d803-11e9-837a-78cf35919a70.png)
![image](https://user-images.githubusercontent.com/30517801/64922573-3bb91e80-d803-11e9-907b-223ffb8295a9.png)

不需要重是label字段

**Comment by zhangyc** [comment]
解决了吗?楼上

**Comment by jwencode** [comment]
我是解决了，就用默认的属性名可以，别用属性那个替换，自己处理数据。



t-junwen@foxmail.com
 
发件人： zhangyc
发送时间： 2019-10-15 09:13
收件人： hql7/tree-transfer
抄送： jwencode; Comment
主题： Re: [hql7/tree-transfer] 为什么左边是树形右边就变成了列表 (#36)
解决了吗?楼上

**Comment by zhangyc** [comment]
解决了


发自网易邮箱大师
在2019年10月15日 10:41，jwencode 写道：
我是解决了，就用默认的属性名可以，别用属性那个替换，自己处理数据。



t-junwen@foxmail.com

发件人： zhangyc
发送时间： 2019-10-15 09:13
收件人： hql7/tree-transfer
抄送： jwencode; Comment
主题： Re: [hql7/tree-transfer] 为什么左边是树形右边就变成了列表 (#36)
解决了吗?楼上

**Comment by hql7** [comment]
![image](https://user-images.githubusercontent.com/23188802/67455912-9f840200-f661-11e9-9ab5-054886bc80a0.png)
麻烦认真阅读使用说明再使用
