### ISSUE TITLE
filter 自定义搜索不支持大小写模糊搜索

### ISSUE THREAD

**Issue by zhangqijohn** [hql7/tree-transfer#39]

**Comment by zhangqijohn** [comment]
赶项目中，没有经过测试，大概应该是这样的
transfer-extend.vue 文件下
// 源数据 筛选
    filterNodeFrom(value, data) {
      if (!value) return true;
      return data[this.defaultProps.label.toLowerCase()].indexOf(value.toLowerCase()) !== -1;
    },
    // 目标数据筛选
    filterNodeTo(value, data) {
      if (!value) return true;
      return data[this.defaultProps.label.toLowerCase()].indexOf(value.toLowerCase()) !== -1;
    },

**Comment by hql7** [comment]
可以使用自定义筛选
