### ISSUE TITLE
fromData和toData 没有随着tree结构动态更新 

### ISSUE THREAD

**Issue by xingyue234** [hql7/tree-transfer#4]
fromData和toData 只是用来设置默认值得吗，给右边添加值，界面变化了，但是toData 和 fromData还是原来的值

**Comment by xingyue234** [comment]
紧急求助

**Comment by hql7** [comment]
是的 点击按钮的add事件和remove事件会返回你移动了那些数据

**Comment by bitmoonz** [comment]
附议，求增加搜索和排序功能

**Comment by hql7** [comment]
搜索功能已有，排序功能我看看吧

在 2018-08-27 14:33:08，"bitmoonz" <notifications@github.com> 写道：


附议，求增加搜索和排序功能

**Comment by hql7** [comment]
搜索和拖拽已加
