### ISSUE TITLE
右侧选中的数据怎么获得  没明白怎么用？

### ISSUE THREAD

**Issue by zhoufei3512** [hql7/tree-transfer#43]
求各位大佬解释下哇，没明白怎么获得选中的右侧数据

**Comment by hql7** [comment]
如果你是说获取右侧checkbox选中的，
![image](https://user-images.githubusercontent.com/23188802/60225266-a1f36c80-98b8-11e9-994b-b174068b2011.png)；如果你说的是获取穿梭到右侧的数据
![image](https://user-images.githubusercontent.com/23188802/60225278-b172b580-98b8-11e9-94b8-2fb943356041.png)
