### ISSUE TITLE
子节点id是必须是唯一的吗?

### ISSUE THREAD

**Issue by nicoleXue1** [hql7/tree-transfer#47]
当子节点的id不唯一的时候 存在移动数据错乱的情况 不知道是不是这个引起的 谢谢答疑

**Comment by hql7** [comment]
@nicoleXue1 是的，所有id都必须是唯一，穿梭位置以id为判断依据

**Comment by nicoleXue1** [comment]
好的 过滤函数可以自定义吗?  filter-node-method

**Comment by nicoleXue1** [comment]
这边需求是过滤后如果是父节点 展开父节点下面的子节点 这个好像没有自定义过滤函数的地方 谢谢

**Comment by hql7** [comment]
// 自定义筛选函数
    filterNode: Function,
