### ISSUE TITLE
是不是应该吧代码更新一下

### ISSUE THREAD

**Issue by zhangwanqin357** [hql7/tree-transfer#5]
代码跟demo,readme都对应不上，使用的话，有好几个问题：
1. 如果一级数据不存在children的话，左右穿梭会报错；
2. 从左向右穿梭，会出现左边的数据不减少，右边的数据按正常增加，但是从右向左不会出现这种情况（经我个人实验，二级数据的前三条会，后面不会）
3. 明明id没有重叠，但是在从左向右添加时，数据会被添加到其他组。

以上是我个人使用出现的问题，但是由于文档写的不易阅读理解，所以斗胆提出。如有冒犯，请见谅。

**Comment by hql7** [comment]
此代码clone下来运行并未出现上述问题，可否+q详细说明一下当时场景及数据

**Comment by zhangwanqin357** [comment]
已加

**Comment by xincream** [comment]
pid 得跟上一层的id对应 @zhangwanqin357 

现在的版本不能手动清除右边的数据，能否加上 @hql7

**Comment by silence-kb** [comment]
> 代码跟demo,readme都对应不上，使用的话，有好几个问题：
> 
> 1. 如果一级数据不存在children的话，左右穿梭会报错；
> 2. 从左向右穿梭，会出现左边的数据不减少，右边的数据按正常增加，但是从右向左不会出现这种情况（经我个人实验，二级数据的前三条会，后面不会）
> 3. 明明id没有重叠，但是在从左向右添加时，数据会被添加到其他组。
> 
> 以上是我个人使用出现的问题，但是由于文档写的不易阅读理解，所以斗胆提出。如有冒犯，请见谅。

我也出现了这样的问题,请问是如何解决的?
