### ISSUE TITLE
树节点 可以设置check-strictly属性吗

### ISSUE THREAD

**Issue by jwencode** [hql7/tree-transfer#58]
tree check-strictly 不遵循父子关系 
![image](https://user-images.githubusercontent.com/30517801/66122548-924f9680-e612-11e9-95a5-99c6a4570b16.png)

**Comment by hql7** [comment]
@jwencode 我记得是不可以，因为树形穿梭需要依赖父子关系，在没有另外处理的情况下穿梭过去可能树链上缺少节点

**Comment by hql7** [comment]
@jwencode 2.4.1
