### ISSUE TITLE
懒加载设置无效

### ISSUE THREAD

**Issue by Nosaj0620** [hql7/tree-transfer#59]
<tree-transfer ref="transfer" :addressOptions="{num: 1}"
                         :from_data='repData'
                         lazy
                         :lazyFn="loadRep"
                         :to_data='toData'
                         :defaultProps="{label:'name', children: 'children',isLeaf:'leaf'}" @addBtn='add'
                         @removeBtn='remove' :mode='mode'
                         filter>
          </tree-transfer>
这样写的  有什么问题吗  我的节点 不能展开

**Comment by hql7** [comment]
@Nosaj0620 当前app.vue例子已展示懒加载模式，可下载运行，如有问题，请提供可重现最小代码文件

**Comment by Nosaj0620** [comment]
> @Nosaj0620 当前app.vue例子已展示懒加载模式，可下载运行，如有问题，请提供可重现最小代码文件

多谢  已经自己找到问题了  mode我用了通讯录模式 通讯录模式下这个懒加载是不生效的

**Comment by isyoungxl** [comment]
请问下 lazyFn的回调具体咋写哇，我参照tree的懒加载的回调resolve好像不得行，

**Comment by isyoungxl** [comment]
`<tree-transfer
        :from_data="fromData"
        :to_data="toData"
        :defaultProps="{label:'name'}"
        @addBtn="add"
        @removeBtn="remove"
        lazy
        :lazyFn='loadNode'
        :title='["原数据", "目标数据"]'
        height="540px"
        filter
      ></tree-transfer>

//js
loadNode(node,resolve,from) {
      //一级节点处理
      console.log( '================')
      if (node.level === 0) {
        this.getOrganNodes(resolve);
      }
 
    },
`
这样写 压根不进loadNode这个方法哇  请问哪里写错了
