### ISSUE TITLE
如果获取选中和半选中的节点

### ISSUE THREAD

**Issue by jwencode** [hql7/tree-transfer#61]
this.$refs.tree.getCheckedNodes().concat(this.$refs.tree.getHalfCheckedNodes()

getCheckedNodes();
getHalfCheckedNodes();

这两个方法可以吗？

**Comment by hql7** [comment]
@jwencode 不可以
![image](https://user-images.githubusercontent.com/23188802/67910545-1408f480-fbbe-11e9-9d49-6c9ec673d026.png)

**Comment by jwencode** [comment]
@hql7 明白了， 比官方简单多了  赞
