### ISSUE TITLE
勾选事件

### ISSUE THREAD

**Issue by BeImperfect** [hql7/tree-transfer#7]
如何监听CheckBox的勾选事件，<el-transfer>用的是@left-check-change（左侧），那现在换成<tree-transfer>如何监听呢？

**Comment by BeImperfect** [comment]
el-transfer用的是@left-check-change（左侧）,那现在换成tree-transfer该如何监听呢

**Comment by hql7** [comment]
@BeImperfect  并没有做左侧监听事件，可以讲讲你的需求

**Comment by hql7** [comment]
2.0版本已加，返回数据见el-tree的check事件
