### ISSUE TITLE
是否可以增加事件：重置（即清空已选项）

### ISSUE THREAD

**Issue by Patrick-kk** [hql7/tree-transfer#74]
在使用过程中，需要清空已选择项。目前好像只能手动勾选全部，然后移除。

这个动作若想在代码层面完成，貌似做不到。 希望能增加一个reset事件，重置选项。

**Comment by hql7** [comment]
@Patrick-kk good idea 在路上

**Comment by hql7** [comment]
@Patrick-kk v2.2.6
