### ISSUE TITLE
获取穿梭框的所有数据？

### ISSUE THREAD

**Issue by chazex** [hql7/tree-transfer#79]
现在好像没有提供一个可以获取所有fromdata/所有todata的函数，能否提供一个呢

**Comment by chazex** [comment]
现在只能在事件add、remove的参数中获取，感觉有些不方便，谢谢。

**Comment by hql7** [comment]
@chazex 数据本来是由你传入的，没有修改就无需获取，修改了会由子组件emit返回很正常啊。你是基于什么操作环境需要获取源数据呢

**Comment by chazex** [comment]
我使用这个组件用来为用户赋予权限，fromdata放的是用户还没有获得的权限，右边是用户已经拥有的权限，在操作的时候，操作人员可能会多次从fromdata->todata，同样也可能会多次从todata->fromdata，当操作完成时，会点击确定提交，我获取到todata中的所有数据就是最终的结果。使用场景是这样的。

**Comment by hql7** [comment]
那么你点确定之前最后一次收到的emit数据就是最新数据，根据单相传递原则，子组件以emit的方式返回。你将emit的数据管理起来，点确定时取用

发自我的iPhone
