### ISSUE TITLE
树状结构超过3层是不是就无法左右移动

### ISSUE THREAD

**Issue by kriszhang1992** [hql7/tree-transfer#8]
使用该组件，发现只能支持3层树状结构，左右穿梭

**Comment by hql7** [comment]
@kriszhang1992 无限层级

**Comment by 605358264** [comment]
如何设计ID和PID的值呢？发现如果这两个值没设计对，就无法穿梭

**Comment by hql7** [comment]
@605358264 子pid是父id，穿梭时根据pid和id匹配来构建层级
