### ISSUE TITLE
设置默认穿梭一次，只要修改defaultCheckedKeys值，就会调用addBtn事件一次

### ISSUE THREAD

**Issue by familyfp** [hql7/tree-transfer#82]
1.想在addBtn里添加后端请求，但是设置默认值defaultCheckedKeys后，总是会执行一次addBtn事件，导致每次都请求后端一次，能否解决？
2.defaultCheckedKeys第二次设置为空后，视图不更新，this.$forceUpdate()都不行
等待大佬解决

**Comment by hql7** [comment]
defaultCheckedKeys只建议在最初使用一次，另外配合defaultTransfer才会触发addBtn穿梭事件；另外请详细描述下你的需求，频繁修改defaultCheckedKeys及使用defaultTransfer的目的

**Comment by hql7** [comment]
@familyfp

**Comment by hql7** [comment]
@familyfp 不要使用defaultTransfer，手动调用addToAims方法

**Comment by familyfp** [comment]
具体能告知addToAims是如何使用吗？`<tree-transfer style="text-align: left; display: inline-block"
                     :placeholder="'请输入关键词'"
                     :title="title" :from_data='fromData'
                     :defaultProps="{label:'name',key:'id'}"
                     :defaultCheckedKeys="defaultCheckedKeys"
                     :pid="'parentId'"
                     @left-check-change="leftCheckChange"
                     @addBtn='add' @removeBtn='remove' :mode='mode' height='540px'
                     filter
                     @addToAims="addToAims(false)"
                     :defaultTransfer="defaultTransfer"></tree-transfer>`
这样写，defaultTransfer为false,当更改了defaultCheckedKeys时，addToAims不执行

**Comment by hql7** [comment]
想默认执行穿梭时，需要defaultTransfer为true，并且当defaultCheckedKeys穿梭后会再更改时，推荐不使用defaultTransfer而直接 refs['your name'].addToAims(), 如果你默认穿梭这一次不想接受addToAims产生的emit回调，可以传入false：refs['your name'].addToAims(false)



在 2020-04-08 17:28:09，"familyfp" <notifications@github.com> 写道：

具体能告知addToAims是如何使用吗？<tree-transfer style="text-align: left; display: inline-block" :placeholder="'请输入关键词'" :title="title" :from_data='fromData' :defaultProps="{label:'name',key:'id'}" :defaultCheckedKeys="defaultCheckedKeys" :pid="'parentId'" @left-check-change="leftCheckChange" @addBtn='add' @removeBtn='remove' :mode='mode' height='540px' filter @addToAims="addToAims(false)" :defaultTransfer="defaultTransfer"></tree-transfer>
这样写，defaultTransfer为false,当更改了defaultCheckedKeys时，addToAims不执行

**Comment by familyfp** [comment]
非常感谢，现在还有一个问题，数据穿梭后右边树结构是默认展开的，能否设置不默认展开？

**Comment by familyfp** [comment]
不好意思，文档没看仔细，已经找到这个属性了。非常感谢

**Comment by ManyYearsLater** [comment]
你好，我无法设置穿梭框的右边的选中值，请问to_data的格式是什么

**Comment by hql7** [comment]
@ManyYearsLater 右侧格式和左侧是一致的，不具有右边默认选中功能
