### ISSUE TITLE
defaultCheckedKeys 回显错误问题

### ISSUE THREAD

**Issue by DahuaChan** [hql7/tree-transfer#89]
--父节点1
----子节点1-1
----子节点1-2
----子节点1-3
--父节点2
----子节点2-1
----子节点2-2
----子节点2-3

如果我的defaultCheckedKeys=[父节点2,子节点2-1]
在回显的时候会出现左侧**仅有父节点1**，右侧会把父节点2下面的所有子节点带过去的情况

**Comment by hql7** [comment]
@DahuaChan 父子关联时默然选中父节点会穿梭所有其子节点，如要父子不关联v2.4.0+
