### ISSUE TITLE
数据选择上有问题

### ISSUE THREAD

**Issue by rcl4444** [hql7/tree-transfer#9]
使用版本:
![image](https://user-images.githubusercontent.com/19640490/45586429-d8fc2100-b929-11e8-8ab3-2d9da54dca50.png)
结果:
![image](https://user-images.githubusercontent.com/19640490/45586422-c255ca00-b929-11e8-8b54-031738301a88.png)
self_from_data:
`[{"id":1,"label":"查找所有商品","pid":0},{"id":3,"label":"eos管理员门店管理","pid":0,"children":[{"id":51,"label":"门店等级列表","pid":3},{"id":4,"label":"eos管理员门店列表","pid":3}]},{"id":5,"label":"eos管理员供应商管理","pid":0,"children":[{"id":52,"label":"商品价格级别列表","pid":5},{"id":6,"label":"eos管理员供应商列表","pid":5}]},{"id":7,"label":"eos管理员采购管理","pid":0,"children":[{"id":8,"label":"eos管理员采购列表","pid":7}]},{"id":9,"label":"eos管理员代发管理","pid":0,"children":[{"id":10,"label":"eos管理员代发列表","pid":9}]},{"id":11,"label":"eos管理员系统管理","pid":0,"children":[{"id":16,"label":"eos管理员系统日志","pid":11},{"id":15,"label":"eos管理员送货地址","pid":11},{"id":14,"label":"eos管理员系统通知","pid":11},{"id":13,"label":"eos管理员系统参数","pid":11},{"id":12,"label":"eos管理员解析模板","pid":11}]},{"id":18,"label":"eos门店供应商管理","pid":0,"children":[{"id":20,"label":"eos门店财务管理","pid":18},{"id":19,"label":"eos门店供应商综合","pid":18}]},{"id":21,"label":"eos门店商品管理","pid":0},{"id":22,"label":"eos门店订单管理","pid":0,"children":[{"id":26,"label":"eos门店代发订单","pid":22},{"id":25,"label":"eos门店入库单","pid":22},{"id":24,"label":"eos门店采购单","pid":22},{"id":23,"label":"eos门店采购计划单","pid":22}]},{"id":27,"label":"eos门店个人中心","pid":0,"children":[{"id":29,"label":"eos门店消息通知","pid":27},{"id":28,"label":"eos门店账户安全","pid":27}]},{"id":31,"label":"eos仓库门店管理","pid":0,"children":[{"id":33,"label":"eos仓库财务管理","pid":31},{"id":32,"label":"eos仓库门店管理类表","pid":31}]},{"id":34,"label":"eos仓库商品管理","pid":0},{"id":35,"label":"eos仓库订单管理","pid":0,"children":[{"id":38,"label":"eos仓库代发管理","pid":35},{"id":37,"label":"eos仓库出库单","pid":35},{"id":36,"label":"eos仓库采购单","pid":35}]},{"id":39,"label":"eos仓库个人中心","pid":0,"children":[{"id":43,"label":"eos仓库支付管理","pid":39},{"id":42,"label":"eos仓库消息通知","pid":39},{"id":41,"label":"eos仓库账号安全","pid":39},{"id":40,"label":"eos仓库个人信息","pid":39}]},{"id":47,"label":"测试业务功能名称","pid":0},{"id":50,"label":"string","pid":0},{"id":53,"label":"拆单接口","pid":0}]`
self_to_data:
`[{"id":1,"label":"查找所有商品","pid":0},{"id":31,"label":"eos仓库门店管理","pid":0,"children":[{"id":33,"label":"eos仓库财务管理","pid":31},{"id":32,"label":"eos仓库门店管理类表","pid":31}]},{"id":34,"label":"eos仓库商品管理","pid":0},{"id":35,"label":"eos仓库订单管理","pid":0,"children":[{"id":38,"label":"eos仓库代发管理","pid":35}]},{"id":39,"label":"eos仓库个人中心","pid":0,"children":[{"id":43,"label":"eos仓库支付管理","pid":39},{"id":42,"label":"eos仓库消息通知","pid":39},{"id":41,"label":"eos仓库账号安全","pid":39},{"id":40,"label":"eos仓库个人信息","pid":39}]}]`

**Comment by hql7** [comment]
@这是左右两侧默认数据都有这一条，还是这一条穿梭过去左侧没删除？

**Comment by rcl4444** [comment]
@hql7 这一条穿梭过去没删除

**Comment by hql7** [comment]
@rcl4444   pid='pid' node_key='id' 这两个参数用的有问题，你怎么设置的

**Comment by rcl4444** [comment]
@hql7 
`<tree-transfer  
ref="treeTransfer"   
:title="treeTransfer.title"  
:from_data='treeTransfer.fromData'  
:to_data='treeTransfer.toData'  
:defaultProps="{label:'label'}"  
mode='transfer'  
width='800px'  
height='540px'   
filter  
openAll>  
</tree-transfer>`使用的是默认配置

**Comment by rcl4444** [comment]
@hql7 ,请问下,是否该组件不支持初始化的数据绑定功能,仅支持数据的左右穿梭?
需要自己处理左右数据的过滤筛选?

**Comment by hql7** [comment]
是

在 2018-10-07 15:43:32，"rcl4444" <notifications@github.com> 写道：


@hql7 ,请问下,是否该组件不支持初始化的数据绑定功能,仅支持数据的左右穿梭?
需要自己处理左右数据的过滤筛选?
