### ISSUE TITLE
lazy懒加载 不进lazyFn方法 

### ISSUE THREAD

**Issue by isyoungxl** [hql7/tree-transfer#90]
`
<tree-transfer
        :from_data="fromData"
        :to_data="toData"
        :defaultProps="{label:'name'}"
        @addBtn="add"
        @removeBtn="remove"
       lazy
       :lazyFn='loadNode'
        :title='["原数据", "目标数据"]'
        height="540px"
        filter
      ></tree-transfer>
`
`
loadNode(node,resolve,from) {
  
      console.log( '================')
    //   if (node.level === 0) {
    //     this.getOrganNodes(resolve);
    //   }
 
    },
`

发现压根不进loadNode这个方法，请问我哪里写错了吗

**Comment by isyoungxl** [comment]
不使用lazf方法使用普通数据，却又可行，请问懒加载还需要配置什么吗

**Comment by hql7** [comment]
建议不要使用懒加载
