### ISSUE TITLE
@addBtn和@removeBtn从驼峰改为用-分开（add-btn）之后点击事件不触发

### ISSUE THREAD

**Issue by zjjdegit** [hql7/tree-transfer#93]
![image](https://user-images.githubusercontent.com/31202392/81906034-2f869a80-95f8-11ea-9f55-db5dfb143082.png)
addSys和removeSys将不再被触发

**Comment by EdisonYoung23** [comment]
请问解决了吗？这个问题

**Comment by hql7** [comment]
@EdisonYoung23 @zjjdegit v2.4.1
